env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
os:
  - linux
  - osx
language: rust
rust:
  - 1.26.2
  - nightly-2018-06-10
sudo: false
branches:
  only:
    - master
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - if [[ $TRAVIS_RUST_VERSION =~ ^nightly.* && $TRAVIS_OS_NAME == linux ]]; then
      bash cargo_install.sh rustfmt-nightly 0.8.2;
      bash cargo_install.sh clippy 0.0.207;
    fi
script:
  - if [[ ! $TRAVIS_RUST_VERSION =~ ^nightly.* ]]; then
      (
        set -x;
        cargo test --verbose --release &&
        cargo test --verbose --release --features mock
      );
    elif [[ $TRAVIS_OS_NAME == linux ]]; then
      (
        set -x;
        cargo fmt -- --check &&
        cargo clippy --verbose --all-targets
      );
    fi
before_cache:
 - cargo prune
