[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A convenience library providing abstractions for cryptographic functions."
homepage = "https://maidsafe.net"
license = "MIT OR BSD-3-Clause"
name = "safe_crypto"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_crypto"
version = "0.2.0"

[dependencies]
lazy_static = { version = "~1.0.1", optional = true }
maidsafe_utilities = "~0.15.0"
quick-error = "~1.2.2"
rand = { version = "~0.4.2", optional = true }
rust_sodium = "~0.9.0"
serde = "~1.0.66"
serde_derive = "~1.0.66"
tiny-keccak = "~1.4.2"
unwrap = "~1.1.0"

[dev-dependencies]
rand = "~0.4.2"

[features]
mock = ["rand", "lazy_static"]
